.RECIPEPREFIX = >

pbxTeleporter: pbxTeleporter.c udpServer.c udpServer.h pbxSerial.c pbxSerial.h pbxSerial.h cmdline.h cmdline.c
> gcc -Wall -pthread -o pbxTeleporter pbxTeleporter.c udpServer.c pbxSerial.c cmdline.c
    
